# Generated by Django 6.0.2 on 2026-05-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Доступна'),
                    ('pending_approval', 'Ожидает подтверждения'),
                    ('assigned', 'Назначена'),
                ],
                default='available',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='student',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_topics',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Студент',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='teacher_topics',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Преподаватель',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(
                choices=[('vkr', 'ВКР'), ('coursework', 'Курсовая работа')],
                default='coursework',
                max_length=20,
                verbose_name='Тип темы',
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to='topics/', verbose_name='Файл')),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='topics.topic',
                        verbose_name='Тема',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Файл темы',
                'verbose_name_plural': 'Файлы темы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicApplication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидает решения'),
                            ('approved', 'Одобрена'),
                            ('rejected', 'Отклонена'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='Статус заявки',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_applications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Студент',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to='topics.topic',
                        verbose_name='Тема',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявка на тему',
                'verbose_name_plural': 'Заявки на темы',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['student', '-created_at'],
                        name='topics_topi_student_4e0fcb_idx',
                    ),
                    models.Index(
                        fields=['topic', 'status'],
                        name='topics_topi_topic_i_868004_idx',
                    ),
                    models.Index(
                        fields=['student', 'status'],
                        name='topics_topi_student_eda3e9_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='TopicStep',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название этапа'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Описание этапа'),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='steps',
                        to='topics.topic',
                        verbose_name='Тема',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Этап темы',
                'verbose_name_plural': 'Этапы тем',
                'ordering': ['order', 'id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('topic', 'order'), name='unique_topic_step_order'
                    )
                ],
            },
        ),
    ]
