# Generated by Django 6.0.2 on 2026-05-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_options_topic_status_topic_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicstep',
            name='description',
        ),
    ]
