# Generated by Django 6.0.2 on 2026-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topicstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicfile',
            name='original_name',
            field=models.CharField(
                default='',
                editable=False,
                max_length=255,
                verbose_name='Оригинальное имя файла',
            ),
            preserve_default=False,
        ),
    ]
