# Generated by Django 6.0.2 on 2026-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topicfile_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicfile',
            name='original_name',
            field=models.CharField(
                default='',
                editable=False,
                max_length=255,
                verbose_name='Оригинальное имя файла',
            ),
        ),
    ]
