# Generated by Django 6.0.2 on 2026-05-15 14:23

import topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topicfile_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicfile',
            name='file',
            field=models.FileField(
                upload_to=topics.models.topic_file_path, verbose_name='Файл'
            ),
        ),
    ]
