# Generated by Django 6.0.2 on 2026-04-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='группа'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.PositiveSmallIntegerField(
                choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')],
                verbose_name='Курс',
            ),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='users.studentgroup',
                verbose_name='Группа',
            ),
        ),
    ]
