# Generated by Django 6.0.2 on 2026-04-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentgroup_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='ученая степень'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ученая степень',
                'verbose_name_plural': 'Ученые степени',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='ученое звание'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ученое звание',
                'verbose_name_plural': 'Ученые звания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='должность'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_degree',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='teacher_profiles',
                to='users.academicdegree',
                verbose_name='Ученая степень',
            ),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_title',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='teacher_profiles',
                to='users.academictitle',
                verbose_name='Ученое звание',
            ),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='job_title',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='teacher_profiles',
                to='users.jobtitle',
                verbose_name='Должность',
            ),
        ),
    ]
